### ISSUE TITLE
NullPointerException when using higher-order quantification inside the evaluator

### ISSUE THREAD

**Issue by sorawee** [aleksandarmilicevic/hola#6]
From a student in our class:

Consider

```alloy
sig A {
  v: A
}

run {}
```

In any instance, evaluate `all x : v | some x` in the evaluator. This results in 

```
Fatal error:
Unknown exception occurred:
java.lang.NullPointerException
```

**Comment by aleksandarmilicevic** [comment]
Thanks, I'll look at it.  I'll fix the NPE, but I doubt I'll implement support for evaluating higher-order quantifiers inside the evaluator.
