### ISSUE TITLE
Type constraint results in NullPointerException

### ISSUE THREAD

**Issue by sorawee** [aleksandarmilicevic/hola#8]
From a student in our class.

Consider:

```
sig A {
  b: A,
  c: set A + b
}

run {}
```

This works fine in Alloy, but not Alloy*.

**Comment by conrad-watt** [comment]
Hi! We're trying to use Alloy*. and we're also running into this issue. We're trying to do something like this:

```
sig A {
}

sig B {
  b: A,
  c: A,
  d: b+c
}

run {}
```

We can work around this by restricting (e.g.) d afterwards, but this generates a lot of boilerplate in our larger models.

**Comment by aleksandarmilicevic** [comment]
Sorry for taking this long to fix this. 

It should work fine now.
